language: node_js
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#- sudo sh -c 'echo "deb http://deb.opera.com/opera/ stable non-free" >> /etc/apt/sources.list.d/opera.list'
#- sudo sh -c 'wget -O - http://deb.opera.com/archive.key | apt-key add -'
#- sudo sh -c 'wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
#- sudo apt-get update
#- sudo apt-get install opera
node_js:
- 0.1
deploy:
  provider: heroku
  app: angularjs-crypto
  strategy: git
  api_key:
    secure: nQ9G863kXSWi+AC/Xreiz1/bGTikFfU+0MNQY6NkvMh3A7vJjQP52cpOcVsSnJi8oekTYrbJDj/aswSSXSoJI5ftvxjBU5GwGyB6gjJQRtMGMn3IBgc9X19vW4NGqX5Y2aQRoJOfHy2A1sKrkycfEdy/x8Z3jhoPHG1+Pi0lLNQ=
after_failure:
- ./upload_junitreport.sh
before_deploy:
- ./upload_junitreport.sh
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/69a4be3312f3f3a0a25b
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
  - secure: UCE+iAMEYy0lsptBFe643/RPL23xbW3QelvgOdR/m8KKVT/N6BcsHyzgtKY2Sr4HHuL17zoVr/RFbkCfN9/u//Zfudl7p/LgdccCXMsyWXy5L2ovGquRsS4iN3glFKG+PKl7l+Qe7F6wueVjWsGmjAB+P/xFEzmYCtAMxD42YLU=
  - secure: MPzm10FDUGNdhH4SPk/yiJbEMnwPW0cNN09Gq0gIFX6VY7hhHIMjgYXtmD1lIVPevtdP2+m9z1OrpNo13VExZz9srx3h449E6W8/w7SxQRGjAcS/wNZhl9Nztf2xk/nwMW8VVwD8i5wJFVjkCfni7ZspfYlZ8mZuo6pLfk5MCbs=
